apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gendeck.fullname" . }}-config
  labels:
    {{- include "gendeck.labels" . | nindent 4 }}
data:
  PORT: "3001"
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
