apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gendeck.fullname" . }}-frontend
  labels:
    {{- include "gendeck.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.frontend.enabled }}
  replicas: {{ .Values.replicaCount.frontend }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gendeck.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gendeck.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "gendeck.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "gendeck.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "gendeck.frontend.image" . | quote }}
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: VITE_API_URL
              value: {{ .Values.backend.apiUrl | quote }}
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          {{- if .Values.probes.frontend.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.frontend.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.frontend.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.frontend.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.frontend.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.frontend.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.frontend.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.frontend.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.frontend.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.frontend.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.frontend.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.frontend.readiness.failureThreshold }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
